### ISSUE TITLE
Configure Azure Pipeline

### ISSUE THREAD

**Issue by ricardogobbosouza** [webpack-contrib/eslint-webpack-plugin#1]
Hi @evilebottnawi 
Can configure azure pipeline?

**Comment by evilebottnawi** [comment]
WIP

**Comment by evilebottnawi** [comment]
Done https://dev.azure.com/webpack/eslint-webpack-plugin/_build/results?buildId=6980

**Comment by evilebottnawi** [comment]
Feel free to drop `node@8` for first release and update CI template

**Comment by evilebottnawi** [comment]
I don't know what is hell with github but i got 500 and a PR was merged, feel free to remove this https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/.editorconfig#L1 in other PR :confused:

**Comment by ricardogobbosouza** [comment]
@evilebottnawi  thanks
