### ISSUE TITLE
3.0.0 throws ERR_REQUIRE_ESM on use

### ISSUE THREAD

**Issue by jsg2021** [webpack-contrib/eslint-webpack-plugin#106]
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/jonathan/Workspace/nti/node_modules/eslint-webpack-plugin/node_modules/arrify/index.js
require() of ES modules is not supported.
require() of /home/jonathan/Workspace/nti/node_modules/eslint-webpack-plugin/node_modules/arrify/index.js from /home/jonathan/Workspace/nti/node_modules/eslint-webpack-plugin/dist/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/jonathan/Workspace/nti/node_modules/eslint-webpack-plugin/node_modules/arrify/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/jonathan/Workspace/nti/node_modules/eslint-webpack-plugin/node_modules/arrify/package.json.
```
Sure enough, the import was converted to require...
https://unpkg.com/browse/eslint-webpack-plugin@3.0.0/dist/utils.js

**Comment by jsg2021** [comment]
After dropping node 10, does this still include node 11 (non-lts)? if not, does this still need transpiling?

**Comment by alexander-akait** [comment]
Only 12 is valid https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/package.json#L17

**Comment by jsg2021** [comment]
That's what I was getting at. The transformed code doesn't work on 12+

**Comment by alexander-akait** [comment]
Ah, I see, let's remove this package from our code, we don't need extra package we this simple action https://github.com/sindresorhus/arrify/blob/main/index.js

**Comment by xavierfoucrier** [comment]
Yep, same on my side.
Let me know if you need another beta-tester :wink:

**Comment by xavierfoucrier** [comment]
@alexander-akait same error with `stylelint-webpack-plugin` upgrade to `v3.0.0`, also related to `arrify`.

**Comment by 243083df** [comment]
`(function (exports, require, module, __filename, __dirname) { export default function arrify(value) {
                                                              ^^^^^^

SyntaxError: Unexpected token 'export'`

**Comment by wadakatu** [comment]
I got same error.
Moreover, I changed two files below, and the error does not show up.
However, I am not 100% sure that it is right solution.
If it is bad one, please let me know.

1. node_modules/arrify/index.js
2. node_modules/arrify/package.json

```
1. arrify/index.js ---> change file name to arrify/index.cjs  

module.exports = function arrify(value) {
    if (value === null || value === undefined) {
        return [];
    }
    if (Array.isArray(value)) {
        return value;
    }
    if (typeof value === 'string') {
        return [value];
    }
    if (typeof value[Symbol.iterator] === 'function') {
        return [...value];
    }
    return [value];
}

```

```
2. package.json

{
    “name”: “arrify”,
    “version”: “3.0.0",
    “description”: “Convert a value to an array”,
    “license”: “MIT”,
    “repository”: “sindresorhus/arrify”,
    “funding”: “https://github.com/sponsors/sindresorhus”,
    “author”: {
        “name”: “Sindre Sorhus”,
        “email”: “sindresorhus@gmail.com”,
        “url”: “https://sindresorhus.com”
    },
    “type”: “module”,
    “exports”: “./index.cjs”,   <------change from `index.js` to `index.cjs`.
    “engines”: {
        “node”: “>=12"
    },
    “scripts”: {
        “test”: “xo && ava && tsd”
    },
    “files”: [
        “index.js”,
        “index.d.ts”
    ],
    “keywords”: [
        “array”,
        “arrify”,
        “arrayify”,
        “convert”,
        “value”,
        “ensure”
    ],
    “devDependencies”: {
        “ava”: “^3.15.0",
        “tsd”: “^0.14.0",
        “xo”: “^0.39.1"
    }
}
```

**Comment by alexander-akait** [comment]
Fixed, but I don't have access to https://www.npmjs.com/package/eslint-webpack-plugin, so I can't publish... Need wait @ricardogobbosouza

**Comment by alexander-akait** [comment]
Done https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v3.0.1, please try

**Comment by xavierfoucrier** [comment]
@alexander-akait works fine both `eslint-webpack-plugin` and `stylelint-webpack-plugin` :wink:
