### ISSUE TITLE
update to 3.0.0 breaks webpack build

### ISSUE THREAD

**Issue by bahtou** [webpack-contrib/eslint-webpack-plugin#107]
- Operating System: OSX 10.15.7
- Node Version: 16.5.0
- NPM Version: 7.19.1
- webpack Version: 5.44.0
- eslint-webpack-plugin Version: 3.0.0

### Expected Behavior

`eslint-webpack-plugin` to work with `webpack": "^5.44.0`

### Actual Behavior

`ESLintPlugin()` throws error when webpack builds

### How Do We Reproduce?

Follow `README.md`

https://github.com/bahtou/issues/tree/eslint-webpack-plugin

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/eslint-webpack-plugin/issues/106, please look at issues before post

**Comment by bahtou** [comment]
sorry  took me about an hour to file this issue   thanks
