### ISSUE TITLE
The eslint-webpack-plugin can work normally even without eslint installed.

### ISSUE THREAD

**Issue by Chorer** [webpack-contrib/eslint-webpack-plugin#116]
- Operating System: windows 10
- Node Version:  v16.5.0
- NPM Version:  v7.19.1
- webpack Version:  v4.41.0
- eslint-webpack-plugin Version:   v2.5.0

### Expected Behavior

The eslint-webpack-plugin will throw an error saying there is no eslint installed.

### Actual Behavior

I don't install eslint locally or globally. But the eslint-webpack-plugin can work normally even without eslint installed.

**Comment by alexander-akait** [comment]
`NPM Version: v7.19.1` is installed `Peer dependencies` automatically, please read https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies, so expected
