### ISSUE TITLE
ESLint - No errors or warnings through webpack plugin, works using cli.

### ISSUE THREAD

**Issue by zgjimgjonbalaj** [webpack-contrib/eslint-webpack-plugin#134]
### Bug report

For some reason ESLint Webpack plugin does not product any errors or warnings during build. Have not been able to locate anything related to this issue specifically anywhere. Have tried just about every option, approach to get this to work unsuccessfully. I tried debugging using node-nightly at some point and noticed that there was an error produced regarding a promise.

Note: Downgrading to plugin version 2.1.0 and the appropriate eslint version (I believe it was 7.0) does seem to work. Found this solution in some forum, with that version however it does not lint only the files webpack is iterating through but relies on a path to traverse through.

### Actual Behavior

Running `npx webpack --config webpack.config.js` within the same dir works fine and am able to produce the right JS files with all other plugins. ESLint Webpack Plugin however does not produce any warnings or errors. It is visible in the stats during build as seen below: 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/60440190/144720496-1c9760d5-4547-4bb3-9522-9d73a6631990.png">
(this screengrab was captured with webpack stats configured but did not include that in the webpack.config.js, can provide if needed)

### Expected Behavior

ESLint should produce errors and warnings based on the rules set forth in .eslintrc.js and stop the build process. It should display reasons for failure and each occurrence of that rule failure as usual.

### How Do We Reproduce?

Use this `webpack.config.js` file https://pastebin.com/GM9SuwE6
Use this `package.json` file https://pastebin.com/eDeeD6c8
Use this `.eslintrc.js` file https://pastebin.com/tVfv5Fs4

1. Install node packages and download the webpack config and eslintrc file into same dir. 
2. Create any JS file that would fail the indent rule defined in .eslintrc.js and place one level above the files (not sure if folder structure has an impact but did not test otherwise)
3. Edit line 7 in the `webpack.config.js` file to reflect the name and location of your new JS file.
4. Run `npm run build`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 7.44 GB / 32.00 GB
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    npm: 8.2.0 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Brave Browser: 96.1.32.113
    Chrome: 96.0.4664.55
    Firefox: 94.0.2
    Safari: 15.1
  Packages:
    babel-loader: ^8.2.3 => 8.2.3
    eslint-webpack-plugin: ^3.1.1 => 3.1.1
    webpack: ^5.64.4 => 5.64.4
    webpack-cli: ^4.9.1 => 4.9.1
    webpack-dev-server: ^4.6.0 => 4.6.0

**Comment by zgjimgjonbalaj** [comment]
Turns out that it has everything to do with the file being one level up from the webpack folder. Once you move that JS file/Webpack entry into the same level as webpack, it works and i get an error on my .eslintrc.js file. After I fixed that the output is correct.

**Comment by zgjimgjonbalaj** [comment]
Adding the option `context` and `overrideConfigFile` seems to work now.

**Comment by ricardogobbosouza** [comment]
Hi @zgjimgjonbalaj 
Sorry for the late reply.
But this is in the docs under the [context](https://github.com/webpack-contrib/eslint-webpack-plugin#context)
