### ISSUE TITLE
Exclude files

### ISSUE THREAD

**Issue by peterwiebe** [webpack-contrib/eslint-webpack-plugin#15]
- Operating System: macOS 10.15.5
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.34.0
- eslint-webpack-plugin Version: 2.1.0

### Feature Proposal
Exclude files based on glob pattern.

### Feature Use Case
It was useful to be able to exclude certain files (using eslint-loader) during the build process because they aren't used for deployment purposes. Adding them to .eslintignore is not desirable because they should still be linted during development.

**Comment by zoxon** [comment]
Please implement this ASAP.
In case when source files and node_modules in same directory it doesn't work
https://github.com/nuxt-community/eslint-module/issues/45
