### ISSUE TITLE
No option to perform a full initial lint and later on only dirty modules

### ISSUE THREAD

**Issue by maolimu** [webpack-contrib/eslint-webpack-plugin#151]
### Feature Proposal

Currently, there is no way to have a full initial linting and afterwards linting of changed modules.
lintDirtyModulesOnly if enabled, skips the initial linting.

Suggestion for easier backwards compatibility, make lintDirtyModulesOnly accept an option: "enabledWithFullInitialLinting" in adition to the current true and false

### Feature Use Case

Users using the esling plugin and webpack in watch mode start development with a full compilation, which should show any linting warnings. After initial compilation, changed modules should be re-checked. 

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 249.22 MB / 16.00 GB
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: 100.0.1185.50
    Safari: 15.4

**Comment by ricardogobbosouza** [comment]
Hi @maolimu 
I don't know if I understand well what that option would be.
But by default the initial lint is complete and then only on changed modules
