### ISSUE TITLE
ERR_INVALID_ARG_TYPE - @3.1.1

### ISSUE THREAD

**Issue by shmolf** [webpack-contrib/eslint-webpack-plugin#156]
### Actual Behavior

While running the `eslint`er, and having specified the `eslint-webpack-plugin` in ESLint configuration, I encounter the following error:
```
ESLint: 7.32.0

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.isAbsolute (path.js:353:5)
    at isFilePath (C:\Users\nicholas\Prog_Projects\noted\node_modules\@eslint\eslintrc\lib\config-array-factory.js:132:14)
    at C:\Users\nicholas\Prog_Projects\noted\node_modules\@eslint\eslintrc\lib\config-array-factory.js:907:17
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (C:\Users\nicholas\Prog_Projects\noted\node_modules\@eslint\eslintrc\lib\config-array-factory.js:906:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\nicholas\Prog_Projects\noted\node_modules\@eslint\eslintrc\lib\config-array-factory.js:726:44)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\nicholas\Prog_Projects\noted\node_modules\@eslint\eslintrc\lib\config-array-factory.js:666:20)
    at _normalizeObjectConfigData.next (<anonymous>)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

Ideally, when running the linter, there would not be an error related to the ESLint configuration.

### How Do We Reproduce?

Clone [the repository @ the given commit](https://github.com/shmolf/noted/tree/a6136929f764b8137c209a181219372c3cf9f35a). However, there's an issue with the `package.json` at this commit. Need to [update the specified filepath](https://github.com/shmolf/noted/blob/a6136929f764b8137c209a181219372c3cf9f35a/package.json#L85) from `./.eslintrc.json` to `./.eslintrc.js`, since the configuration was recently switched to a different filetype.

After cloning the repo at that commit, and updating the line specified above, run `yarn eslint`.

### Output of `npx webpack-cli info`
```
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 15.64 GB / 31.85 GB
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.24.2 - ~\Prog_Projects\noted\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.22000.120
  Packages:
    file-loader: ^6.2.0 => 6.2.0
    raw-loader: ^4.0.2 => 4.0.2
    sass-loader: ^10.1.1 => 10.2.1
    ts-loader: ^9.0 => 9.2.8
    url-loader: ^4.1.0 => 4.1.1
    webpack-notifier: ^1.13.0 => 1.15.0
    worker-loader: ^3.0.8 => 3.0.8
```

### Additional References
- [Original discussion thread](https://github.com/webpack/webpack/discussions/15745)
- [ESLint configuration](https://github.com/shmolf/noted/blob/a6136929f764b8137c209a181219372c3cf9f35a/.eslintrc.js) at the given commit

**Comment by ricardogobbosouza** [comment]
Hi @shmolf 
This is a plugin for webpack, don't for eslint
See https://github.com/webpack-contrib/eslint-webpack-plugin#getting-started

**Comment by shmolf** [comment]
@ricardogobbosouza Those are the instructions I followed.
- [Plugin is installed](https://github.com/shmolf/noted/blob/a6136929f764b8137c209a181219372c3cf9f35a/package.json#L70) via yarn
- Plugin is [setup in the eslint config](https://github.com/shmolf/noted/blob/a6136929f764b8137c209a181219372c3cf9f35a/.eslintrc.js)

If there's more steps needed, I'm not aware of them.
If I've gone beyond the steps in the wrong direction, I don't understand how/where.

@alexander-akait seems to thing this is a bug and [warrants an Issue be created](https://github.com/webpack/webpack/discussions/15745#discussioncomment-2670521). Maybe they'll have more insight as to why the expected behavior is not being satisfied.

**Comment by shmolf** [comment]
Oh.... I totally missed it. This is a plugin for webpack... **and** should be configured within Webpack, not ESLint.

That original phrasing was misleading, though technically accurate. Since the plugin is the glue between Webpack and ESLint, I saw it as "being for Webpack" meant that it's a plugin for ESLint to support Webpack.

I'll update my ESLint & Webpack configs later, and see how it turns out. Thank you @ricardogobbosouza .
