### ISSUE TITLE
Documentation: How is error reporting "auto adjusted" depending on eslint errors/warnings counts?

### ISSUE THREAD

**Issue by zenflow** [webpack-contrib/eslint-webpack-plugin#158]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

In the README, this is confusing:

> By default the plugin will auto adjust error reporting depending on eslint errors/warnings counts. You can still force this behavior by using emitError or emitWarning options:

It's not clear what adjustment is made and under what exact conditions..
Am I to understand that the defaults for `emitError` and `emitWarning` will be changed in some circumstances?
Can I force a consistent behavior by setting these options to their documented defaults?

### Your Proposal for Changes

Not sure of exact changes, as I am still confused.

**Comment by ricardogobbosouza** [comment]
You may want to not issue the errors or warnings.
This will influence the error and warning report at the end.
