### ISSUE TITLE
Error with eslint error detection

### ISSUE THREAD

**Issue by kenyk7** [webpack-contrib/eslint-webpack-plugin#172]
### Bug report

Error with eslint error detection

### Actual Behavior

Error detection gets stuck in cache or something similar

### Expected Behavior

That the error detection continues without problems.

### How Do We Reproduce?

The problem occurs when I declare a variable at the beginning with errors(var asd = 'asd', in this case the linter detects the errors of no-var and prettier the ";"), then I correct the error of prettier(var asd = ' asd';) the non-var remains, then I comment out the lines(// var asd = 'asd';) in theory there are no errors, but the compiler sticks with the no-var error and does not detect it again more errors (that last one gets stuck), another thing is that sometimes you have to repeat the process a couple of times until you get the error that the error gets stuck and then it doesn't work anymore and you have to restart the server (the idea is not to restart).

Another way is to start the server(yarn dev) with the start error(var asd = 'asd'), in this case the eslint errors appear, but when commenting the line(// var asd = 'asd') the errors they get stuck in the console.

You can replicate the error on the following github:

https://github.com/kenyk7/my-config-next

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 5.75 GB / 15.86 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.1566
  Packages:
    eslint-webpack-plugin: ^3.2.0 => 3.2.0

### Error capture and code

you can notice in the capture that the error
- Unexpected var, use let or const instead no-var
appears twice in a row

![image](https://user-images.githubusercontent.com/6136430/178794668-3b8bb5ce-dce9-4b33-af9d-b20d0fbfbe3e.png)

**Comment by ricardogobbosouza** [comment]
Hi @kenyk7 
Sorry for delay..

I couldn't reproduce. If the problem persists, please create a reproduction with webpack only
