### ISSUE TITLE
Error if package.json is not in parent directory to the linted code

### ISSUE THREAD

**Issue by trumko** [webpack-contrib/eslint-webpack-plugin#177]
After updating `eslint-plugin-import` from `2.22.1` to `2.23.0 `or higher the `eslint-plugin-import` breaks with warning:

`ERROR in [eslint] The "path" argument must be of type string. Received null`

After some investigation it looks like the reason is in the file structure when `package.json` file is not in the parent directory to the linted code:

```
myProject
├── build
  ├──  node_modules 
  ├──  package.json # is not in the parent directory to  source folder
  └──  [webpack.config.js, .eslintrc.js and other config files]
└── source
  └── modules #.js files, which should be linted
```
Interestingly, when I create a `package.json` file (which contains only empty `{}`) in the `myProject` folder, everything works as expected.

I just created minimal [reproduction](https://github.com/trumko/eslintMinimalReproduction):

1. Download repo
2. Go to `/build` folder
3. Run `npm install`
4. Run `npm start`

You should see the next error:

```
ERROR in [eslint] The "path" argument must be of type string. Received null
Occurred while linting [folder]\webpack-boilerplate-master\app\index.js:1
Rule: "import/no-extraneous-dependencies"
```

Is there any solution how to make it work correctly with a similar file structure?
I created a [similar issue](https://github.com/import-js/eslint-plugin-import/issues/2510) in `eslint-plugin-import` repository, but I was told that this issue is out of the scope of `eslint-plugin-import` plugin.

**Comment by ricardogobbosouza** [comment]
Hi @trumko 
Sorry for delay...
This is not a problem with `eslint-webpack-plugin`

Try running eslint directly and the same error will occur

1. Download repo
2. Go to `/build` folder
3. Run ` npm install`
4. Run `npx eslint ../app/* -c ./.eslintrc.js`

Possibly an issue with [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import)

**Comment by trumko** [comment]
@ricardogobbosouza isn't the same error occurs because of 
```
    'import/resolver': {
      webpack: {
        config: path.join(__dirname, 'webpack.config.js')
      }
    },
```
in .eslintrc.js config?
