### ISSUE TITLE
Add support to the new eslint.config.js format

### ISSUE THREAD

**Issue by Gabriel-Dias-Oliveira** [webpack-contrib/eslint-webpack-plugin#190]
### Feature Proposal

Recently, Eslint received a new configuration file format [Eslint flat config](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new). It would be nice if the Eslint plugin recognized it as a valid configuration file. 
I tried to use this, however, after setup everything up, I was able to use the rules on the format, but the webpack was not recognizing it as a valid file.
The following message was showing up:
**ERROR in [eslint] No ESLint configuration found in...**

Since I don't receive this error while using a **.json** file and all the rules are running okay, I'd say that the plugin don't support this type of file.

### Feature Use Case

This feature will be very useful since the **Eslint flat config** seems to be promising and easier to maintain.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 5.32 GB / 15.78 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.52)  
    Internet Explorer: 11.0.19041.1566
  Packages:
    copy-webpack-plugin: ^11.0.0 => 11.0.0
    esbuild-loader: ^2.20.0 => 2.20.0
    eslint-webpack-plugin: ^3.2.0 => 3.2.0
    file-loader: ^6.2.0 => 6.2.0
    html-loader: ^4.2.0 => 4.2.0
    html-loader-jest: ^0.2.1 => 0.2.1
    html-webpack-plugin: ^5.5.0 => 5.5.0
    raw-loader: ^4.0.2 => 4.0.2
    webpack: ^5.74.0 => 5.74.0
    webpack-cli: ^4.10.0 => 4.10.0
    webpack-ext-reloader: ^1.1.9 => 1.1.9
    webpackbar: ^5.0.2 => 5.0.2
    zip-webpack-plugin: ^4.0.1 => 4.0.1

**Comment by pgnd** [comment]
similarly, updated
```

Operating System: Linux 6.2 Fedora Linux 38 (Thirty Eight)
Node Version: v18.16.0
NPM Version: 9.5.1
webpack Version: 5.80.0
eslint Version: 8.39.0
eslint-webpack-plugin Version: 4.0.1

cd /path/to/app
ls -al eslint.* webpack.*
	-rw------- 1 wwwrun www 8.2K Apr 25 08:03 webpack.config.mjs
	-rw-rw---- 1 wwwrun www 3.1K Apr 24 12:28 eslint.config.js

yarn webpack --mode=development --progress --profile
	...
	ERROR in [eslint] No ESLint configuration found in /path/to/app/assets/js.

	webpack 5.80.0 compiled with 1 error in 422 ms

cat eslint.config.js

	import js from "@eslint/js";
	import { FlatCompat } from "@eslint/eslintrc";
	import path from "path";
	import { fileURLToPath } from "url";
	const __filename = fileURLToPath(import.meta.url);
	const __dirname = path.dirname(__filename);
	const compat = new FlatCompat({ baseDirectory: __dirname });
	export default [
		{
			ignores: [
			...
	...

```

--> 
* option to find/recognize/support existing ```eslint.config.js``` flat config
* option to explicitly specify path-to-config

**Comment by alexander-akait** [comment]
PR welcome

**Comment by lesha38** [comment]
Good day! Can you tell me when to expect the release of this feature?

**Comment by zayne-wang** [comment]
Good day! When will this released?

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v4.1.0
