### ISSUE TITLE
WDS significant increase in recompile time after migrating from eslint-loader

### ISSUE THREAD

**Issue by tpettrov** [webpack-contrib/eslint-webpack-plugin#20]
After migrating from eslint-loader and updating eslint to v7 WDS recompile time increased abnormal.

- Operating System: Windows 10
- Node Version: v12.13.1
- NPM Version: 6.12.1
- webpack Version: 4.42.0
- eslint-webpack-plugin Version: 2.1.0
- webpack-dev-server:  3.1.14
- eslint : v.7.0.0

### Expected Behavior

Recompile time stays normal.

### Actual Behavior

Recompile time increased significantly from 1-3 seconds to around 10.

**Comment by evilebottnawi** [comment]
Feel free to send a fix, I think we need clean something

**Comment by ricardogobbosouza** [comment]
Hi @tpettrov 
Did you try to enable option [`lintDirtyModulesOnly`](https://github.com/webpack-contrib/eslint-webpack-plugin#lintdirtymodulesonly) ?

**Comment by tpettrov** [comment]
Hi @ricardogobbosouza 
Just checked it and yes recompile time is probably even faster. Many thanks.
Just a recommendation: probably skip lint on start should be divided from lintDirtyModulesOnly, cause in some scenarios (updating eslint and enabling lintDirtyModulesOnly immediately) will leave some files forever unchecked.

**Comment by elisherer** [comment]
I also tried turning `lintDirtyModulesOnly` on but it failed detecting a change I made like creating an unused variable.

**Comment by CarlosAzocar** [comment]
Same, turning lintDirtyModulesOnly on but it failed detecting changes

**Comment by vegerot** [comment]
@ricardogobbosouza  `lintDirtyModulesOnly` is a nice idea, but I would rather just have the linting be done asynchronously, as is done with the TypeScript checker (and as I describe in https://github.com/webpack-contrib/eslint-webpack-plugin/issues/33#issuecomment-721140369)

**Comment by ricardogobbosouza** [comment]
Hi @vegerot, @CarlosAzocar, @elisherer
Try [v2.2.0](https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v2.2.0)

**Comment by vegerot** [comment]
@ricardogobbosouza thanks!  Looks like the overhead should be must faster now.  As someone that's a little bit anal about compile times, I do still wish this could be done async (like TypeScript).  But this should make it much more bearable
