### ISSUE TITLE
Performance: 4.0 Hot Module Replacement build very slow

### ISSUE THREAD

**Issue by yoyo837** [webpack-contrib/eslint-webpack-plugin#209]
### Bug report

#197 changes caused Hot Module Replacement build to be very slow after save files in dev mode.
### Actual Behavior
HMR consumes a lot of time.

### Expected Behavior

Need to be as responsive fast as before.
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.29 GB / 32.00 GB
  Binaries:
    Node: 16.19.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 109.0.1
    Safari: 16.3
  Packages:
    eslint-import-resolver-webpack: ^0.13.2 => 0.13.2 
```

**Comment by VQH-cmd** [comment]
[Solution here](https://github.com/webpack-contrib/eslint-webpack-plugin/issues/208#issuecomment-1419552443)
```js
new ESLintPlugin({
...
cache: true, // 👈
...
})
```

**Comment by yoyo837** [comment]
> [Solution here](https://github.com/webpack-contrib/eslint-webpack-plugin/issues/208#issuecomment-1419552443)
> 
> ```js
> new ESLintPlugin({
> ...
> cache: true, // 👈
> ...
> })
> ```

Thanks.

**Comment by yoyo837** [comment]
Duplicate of #208

**Comment by MaximeCheramy** [comment]
I already have `cache: true` and the update to version 4.0.0 is now very slow (0.5s with version 3.2.0 to 5s now) when touching a file.
