### ISSUE TITLE
Enable `cache` eslint

### ISSUE THREAD

**Issue by ricardogobbosouza** [webpack-contrib/eslint-webpack-plugin#210]
Reported problems #209, #208 

### Feature Proposal

Enable `cache` eslint by default

### Feature Use Case

Enabling eslint caching by default improves performance

**Comment by korya** [comment]
IMHO the default settings should be optimized for ease of use. This means the cache must be enabled. Otherwise, the plugin makes more harm than good.

**Comment by TrevorSayre** [comment]
If this default is changed, it may be worth mentioning the setting in the [README Options section](https://github.com/webpack-contrib/eslint-webpack-plugin#options) and adding a note about including the default cache location `.eslintcache` in your `.gitignore` and/or any other relevant ignore files.

**Comment by alexander-akait** [comment]
Yeah, somebody wants to send a PR?

**Comment by ricardogobbosouza** [comment]
I'll send

**Comment by AdelFattakhova** [comment]
Cache still doesn't work by default for some reason. Had to set it to `true` explicitly in eslint-webpack-plugin config, and hot module reloading became way faster after that
