### ISSUE TITLE
Angular 15+16 compile gets stuck at "70% sealing finish module graph ESLintWebpackPlugin_1"

### ISSUE THREAD

**Issue by Usama129** [webpack-contrib/eslint-webpack-plugin#223]
I'm using `eslint-webpack-plugin 4.0.1` with Angular 16.0.2, and `webpack-dev-server 4.15.0` and `node v18.16.0`.
My compile process (with webpack-dev-server) succeeds initially and goes to 100%. When I change/edit a .ts or .scss file, the re-compile gets stuck at _**"70% sealing finish module graph ESLintWebpackPlugin_1"**_.

plugin webpack config as follows:

> new ESLintPlugin({
>                 extensions: ["ts"],
>                 failOnWarning: false,
>                 failOnError: true,
>                 emitError: true,
>                 cache: true,
>                 cacheStrategy: "content",
>                 lintDirtyModulesOnly: true,
>                 fix: true
>             })

            
Also encountered on Angular 15 with `eslint-webpack-plugin 3.2.0` and `webpack-dev-server 4.11.1` with `node 16.x`

Things we've tried:
cache properties - nope, not related to cache
fix:true disabled - not related
changing order of plugins - nope
update to node 20 - nope

**Comment by StraightOuttaCrompton** [comment]
I'm having the same issue. Initially succeeds but fails when a file is changed.

Plugin config can be found at https://github.com/ProtonMail/WebClients/blob/main/packages/pack/webpack/plugins.js#L42

Tried similar fixes as above, and the only fix is to not include the plugin at all.

None of my colleagues are affected by this, but I am running the older macbook pro with intel chip.

Any advice would be appreciated 🙏

**Comment by StraightOuttaCrompton** [comment]
Seems o be causing an issue with storybook too https://github.com/storybookjs/storybook/issues/18051

**Comment by dikaso** [comment]
Set `threads` to true.

**Comment by ricardogobbosouza** [comment]
I can't reproduce.
If the problem persists, provide a repository

**Comment by dikaso** [comment]
> Set `threads` to `true`, it helps.

Please note that this can hurt performance (or even cause OOM). A better choice is to use number e.g. set `threads: 2` and `lintDirtyModulesOnly: true`.
