### ISSUE TITLE
Option to run only on files in module graph

### ISSUE THREAD

**Issue by martinkadlec0** [webpack-contrib/eslint-webpack-plugin#23]
- Operating System: Windows 10
- Node Version: 12.19.0
- NPM Version: 6.14.8
- webpack Version: 5.0.0
- eslint-webpack-plugin Version: 2.1.0

### Feature Proposal
One thing I liked about eslint-loader is that it was run only on files in the graph module of the build. That is, if a file wasn't imported anywhere it was ignored.

With eslint-webpack-plugin I need to set up separate files/extensions configuration instead of simply relying on webpack to provide the files.

### Feature Use Case
This is very useful whenever you don't have time to deal with files that are currently not part of the build.

**Comment by jsg2021** [comment]
I second this. I'm struggling to configure this plugin to match the efficacy of the loader.

**Comment by jsg2021** [comment]
My original assumption about this plugin was that it would lint files matched by 'files'/'context' when referenced by webpack... It is counter-intuitive to me that it would just run eslint on the context blindly... I get that's what the command line does, but the webpack build environment is more complex than that.

**Comment by jsg2021** [comment]
I'm researching how to do this. I'll open a PR if I find a way.

**Comment by martinkadlec0** [comment]
@jsg2021 My understanding of webpack internals is only very basic, but here are me thoughts. You need the plugin to get access to the full webpack api (and the advantages this plugin has over the loader), but you also need a mechanism to gather the relevant files, which happens to be pretty much what loaders do.

So perhaps the solution is to do something similar to what https://webpack.js.org/plugins/mini-css-extract-plugin/ does? That is having something like `ESLintPlugin.loader` that you could put to rules to gather the files.

Then you could establish reference access through `NormalModule.getCompilationHooks(compilation).loader` to pass the list of files to the plugin.

I hope I am not pointing you to completely wrong direction though O:)

**Comment by ricardogobbosouza** [comment]
@evilebottnawi 
What is your opinion of having a loader inside this plugin? As @martinkadlec0 said
Ex: `ESLintPlugin.loader`

**Comment by evilebottnawi** [comment]
We don't need loader, because we can do same logic inside plugin without a loader :smile:

**Comment by martinkadlec0** [comment]
I mean, loaders are handled just by another plugin, so it makes sense you can do without it, but the reason I suggested using a loader is that it has already familiar established interface. It would also allow you to put the loader in between other loaders for some rarer use cases 🤔

**Comment by jsg2021** [comment]
Yeah, we can get the file names from events in just the Plug-in. We won't lint transformed code, so we don't need to use a loader. 😊

**Comment by conradfr** [comment]
Hello, so what is the options settings to get the old loader behavior ?

(to be honest this change makes no sense to me)

**Comment by ricardogobbosouza** [comment]
Resolve on v2.2.0
Thanks @jsg2021
