### ISSUE TITLE
Run ESLint only on modified files

### ISSUE THREAD

**Issue by JoseBuendiaDigio** [webpack-contrib/eslint-webpack-plugin#234]
### Feature Proposal

Execute ESLint only on changed files.
I don't want to wait 4 minutes to see the server up without cache.
Maybe is possible to run it in background?

### Feature Use Case

I start devServer and I want to run ESLint only on modified files

**Comment by ricardogobbosouza** [comment]
Hi @JoseBuendiaDigio 

[Enable `lintDirtyModulesOnly` ](https://github.com/webpack-contrib/eslint-webpack-plugin#lintdirtymodulesonly)

```
new ESLintPlugin({
    lintDirtyModulesOnly: true,
})
```
