### ISSUE TITLE
Update for ESLint 9

### ISSUE THREAD

**Issue by FeBe95** [webpack-contrib/eslint-webpack-plugin#249]
### Modification Proposal

ESLint v9.0 has been officially released. It would be nice to bump the peer dependency of this plugin to v9.0.

### Expected Behavior / Situation

Allow for usage with ESLint v9.0.

### Actual Behavior / Situation

Requires ESLint v8.0.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: Windows 10 10.0.22631
    CPU: (32) x64 Intel(R) Core(TM) i9-14900K
    Memory: 41.67 GB / 63.77 GB
  Binaries:
    Node: 18.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  Packages:
    browser-sync-webpack-plugin: ^2.0.1 => 2.3.0
    resolve-url-loader: ^5.0.0 => 5.0.0
    sass-loader: ^12.1.0 => 12.6.0
    source-map-loader: ^5.0.0 => 5.0.0
    vue-loader: ^15.9.5 => 15.11.1
    webpack: >=5.72.1 <6.0.0 => 5.91.0
```

**Comment by alexander-akait** [comment]
@ricardogobbosouza hello, do you have time to help us, look like we don't need many work, thank you

**Comment by ricardogobbosouza** [comment]
Of course, for some reason I'm not being notified when an issue is opened
