### ISSUE TITLE
Update the eslint version to 9

### ISSUE THREAD

**Issue by chathurabuddi** [webpack-contrib/eslint-webpack-plugin#256]
### Modification Proposal

Please update the eslint version to the latest version (9) as this plugin is incompatible with eslint 9.

**Comment by kembly** [comment]
Linking as it relates. The `extensions` needs to be removed from the options for eslint 9 compatibility:

https://github.com/microsoft/vscode-eslint/issues/1823

**Comment by xavierfoucrier** [comment]
Hello @alexander-akait 👋 

Any roadmap for this?
Thanks! 😘

**Comment by ricardogobbosouza** [comment]
Hi @xavierfoucrier 
It has already been done
https://github.com/webpack-contrib/eslint-webpack-plugin/commit/d25e94c90b477d465bf4d7fb6450a9b4ed6936f4

**Comment by xavierfoucrier** [comment]
@ricardogobbosouza 💯 ❤️

**Comment by alexander-akait** [comment]
@ricardogobbosouza Do you need a help with release?

**Comment by alexander-akait** [comment]
Also we need revisit old version of eslint (drop some of them) and default Node.js version https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/package.json#L17 (ideally ">= 18.12.0")

**Comment by ricardogobbosouza** [comment]
Released [v4.2.0](https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v4.2.0)

**Comment by ricardogobbosouza** [comment]
> Also we need revisit old version of eslint (drop some of them) and default Node.js version https://github.com/webpack-contrib/eslint-webpack-plugin/blob/master/package.json#L17 (ideally ">= 18.12.0")

https://github.com/webpack-contrib/eslint-webpack-plugin/issues/256#issuecomment-2124634747

**Comment by xavierfoucrier** [comment]
Hello @ricardogobbosouza 👋 

Unfortunately this release do not seems to meet the new eslint 9 requirements, especially the new configuration file format.
> See https://eslint.org/docs/latest/use/migrate-to-9.0.0#flat-config.

I am having a "ERROR in [eslint] No ESLint configuration found" when trying to compile with the plugin in production mode, when I restore the old eslint configuration file it works great.

```json
"devDependencies": {
  "@eslint/js": "^9.2.0",
  "@stylistic/eslint-plugin": "^2.1.0",
  "eslint": "^9.3.0",
  "eslint-webpack-plugin": "^4.2.0",
  "webpack": "^5.91.0",
  "webpack-cli": "^5.1.4",
  ...
},
```

**Comment by ricardogobbosouza** [comment]
In the next version v5.0.0 the default will be changed
