### ISSUE TITLE
the scan of eslint-webpack-plugin is different from eslint-loader in webpack4

### ISSUE THREAD

**Issue by xkelvinx666** [webpack-contrib/eslint-webpack-plugin#31]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

How to lint the 'compiling files' in webpack4 only. The webpack4  doesn't declare 'context'. If i use eslint-webpack-plugin like demo，it scan all the code even if 'dist'.

### Your Proposal for Changes

eslint-webpack-plugin scan the code which is compiling

**Comment by ricardogobbosouza** [comment]
Hi @xkelvinx666 
Try [v2.2.0](https://github.com/webpack-contrib/eslint-webpack-plugin/releases/tag/v2.2.0)
