### ISSUE TITLE
'(undefined) ESLint is not a constructor',

### ISSUE THREAD

**Issue by zhishaofei3** [webpack-contrib/eslint-webpack-plugin#34]
new ESLintPlugin({
        extensions: ['js', 'vue'],
        formatter: require('eslint-friendly-formatter'),
        emitWarning: true,
      }),

    "webpack": "4.44.1",

  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor',
  '(undefined) ESLint is not a constructor'

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
