### ISSUE TITLE
Error ins ESLint is not a constructor

### ISSUE THREAD

**Issue by Twiggeh** [webpack-contrib/eslint-webpack-plugin#53]
- Operating System:
- Node Version: v15.2.1
- NPM Version: ---
- Yarn Version: 1.22.10
- webpack Version: "^4.42.1",
- eslint-webpack-plugin Version: "^2.4.0"

### Expected Behavior

Not crash :D

### Actual Behavior

Crashes :D
### Code
[Gist](https://gist.github.com/Twiggeh/057a8f8e03a0d7ffbd3d4eb2e9dd4f24)

### How Do We Reproduce?
[Repro](https://github.com/Twiggeh/react-template)

If you are on windows, make a `.env` in `client` and set it to 
```
NODE_ENV=development
BACKEND_URL=http://localhost:5050
```
then run `yarn run debug` in the `client` directory.

**Comment by ricardogobbosouza** [comment]
Hi @Twiggeh 
The version of `eslint` must be >=7.0 as mentioned in the documentation.
See https://github.com/webpack-contrib/eslint-webpack-plugin#install

Need update in `package.json`
https://github.com/Twiggeh/react-template/blob/main/client/package.json#L109
