### ISSUE TITLE
Roadmap v1.0.0:

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/eslint-webpack-plugin#6]
/cc @ricardogobbosouza What is status? Do we have roadmap? I began to receive questions about what to use a plugin or loader, and frankly I do not know what to get :smile:

**Comment by ricardogobbosouza** [comment]
Hi @evilebottnawi 

## Roadmap v1.0.0:
- Migrate on github actions
- Deprecated node 8
- Support typescript

## About plugin
Well, the plugin came to solve some problems:
- Cache with cache-loader (https://github.com/webpack-contrib/eslint-loader/issues/267)
- Cache doesn't bust when .eslintrc changes (https://github.com/webpack-contrib/eslint-loader/issues/214)
- Generate an output report (https://github.com/webpack-contrib/eslint-loader/issues/207)
- Not to mention that we have more control with the plugin

**Comment by evilebottnawi** [comment]
@ricardogobbosouza Glad to hear it, any ETA?

**Comment by evilebottnawi** [comment]
> Migrate on github actions

I will do it :+1:

**Comment by evilebottnawi** [comment]
Done github actions :+1:

**Comment by ricardogobbosouza** [comment]
> @ricardogobbosouza Glad to hear it, any ETA?

Coming soon...
I intend until the weekend =)

**Comment by ricardogobbosouza** [comment]
@evilebottnawi What is your recommendation for adding support to typescript?
- Add type definition file `index.d.ts` inside repo
- Create repository `@types/eslint-webpack-plugin`

**Comment by evilebottnawi** [comment]
We use typescript JSDocs in some repos and generate types inside repo, for example https://github.com/webpack/schema-utils/blob/master/package.json#L23, you can do same

**Comment by ricardogobbosouza** [comment]
Hi @evilebottnawi 
Release [v1.0.0](https://github.com/webpack-contrib/eslint-webpack-plugin)
I added a little comparison with the eslint-loader

**Comment by evilebottnawi** [comment]
@ricardogobbosouza Can we deprecate `eslint-loader` in favor this plugin?

**Comment by ricardogobbosouza** [comment]
@evilebottnawi Theoretically, yes, I have doubts, because many people use the eslint-loader

**Comment by ricardogobbosouza** [comment]
@evilebottnawi I think we should recommend using this plug-in and warn that the `eslint-loader` will be depreciated at the end of the year, what do you think?

**Comment by evilebottnawi** [comment]
@ricardogobbosouza Sounds good, so I suggest do not add `deprecation` message for `npm`, only deprecate repo (no fixes or features) with recommendation to migrate on this plugin

**Comment by ricardogobbosouza** [comment]
@evilebottnawi I'll do it :)

**Comment by ricardogobbosouza** [comment]
I moved this depreciation request to the eslint-loader

https://github.com/webpack-contrib/eslint-loader/issues/337
