### ISSUE TITLE
Development server not reloading on changes to code - "[WDS] Errors while compiling. Reload prevented."

### ISSUE THREAD

**Issue by ShaCP** [webpack-contrib/eslint-webpack-plugin#71]
# Bug report

**If the current behavior is a bug, please provide the steps to reproduce.**

Live reloading is prevented in development server with the error:
"[WDS] Errors while compiling. Reload prevented." 

I'm using this config:

`module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: [
    'airbnb-base',
  ],
  parserOptions: {
    ecmaVersion: 12,
    sourceType: 'module',
  },
  rules: {
  },
};
`

Then do npm start

**What is the expected behavior?**

Live reloading should work in web development server. When I make a change to the code, it should be reflected in the web dev server. I tried using these options: 

`new ESLintPlugin({
      failOnError: false,
      failOnWarning: false
    })
`

It seems like they had no effect (according to the docs, false is the default anyway).

**Other relevant information:**
webpack version:  5.16.0
Node.js version: 10.16.3
Operating System: Windows 10
Additional tools:

**Comment by ricardogobbosouza** [comment]
Resolved v2.5.0
