### ISSUE TITLE
eslint-loader in webpack4 cannot emit all lint errors

### ISSUE THREAD

**Issue by mingluzhang** [webpack-contrib/eslint-webpack-plugin#76]
I know eslint-loader is deprecated by eslint-plugin-webpack, but I'm facing the issue of https://github.com/webpack-contrib/eslint-webpack-plugin/issues/59, so I have to use eslint-loader by now. 
Also as no more issue can be opened in repo of eslint-loader, I open this issue here. Thanks.

- Operating System: Windows10
- Node Version:12.17.0
- NPM Version:6.14.8
- webpack Version:4.43.0
- eslint-webpack-plugin Version:2.4.1
- babel-loader Version: 8.1.0
- eslint-loader Version 4.0.2
- repository for reproducing the issue: https://github.com/mingluzhang/eslint-trouble-shoot

### Expected Behavior

All lint errors should be emitted after starting webpack.

### Actual Behavior

Lint errors in /Core which is not included in working directory of the project cannot be detected and emitted.

### How Do We Reproduce?

Please try this repo: https://github.com/mingluzhang/eslint-trouble-shoot
The root directory of the project is /Project. Files in /Core are also referenced.
To start webpack, go to /Client/Project and run "npm run start".

**Comment by mingluzhang** [comment]
@ricardogobbosouza  Please also check this issue in the same repo of #59 . Thanks a million!

**Comment by alexander-akait** [comment]
Do not duplicate issues and `eslint-loader` is deprecated and unsupported

**Comment by mingluzhang** [comment]
> Do not duplicate issues and `eslint-loader` is deprecated and unsupported

This is not a duplicated issue. #57 is the one about `eslint-plugin-webpack` which has bad effect with `babel-loader`. 
That is also the reason why I still have to use `eslint-loader` which is deprecated.
However, even the `eslint-loader` has bad effect in webpack4.

**Comment by alexander-akait** [comment]
You already have the issue with `babel-loader` https://github.com/webpack-contrib/eslint-webpack-plugin/issues/59, `eslint-loader` is deprecated and no fixes more

**Comment by mingluzhang** [comment]
Fine. Hope `eslint-plugin-webpack` can solve all my issues.

**Comment by alexander-akait** [comment]
I will look your issue late (today)

**Comment by mingluzhang** [comment]
> I will look your issue late (today)

Thanks a lot. Though `eslint-loader` is a temporary solution, I hope it can be run perfectly.
