### ISSUE TITLE
Roadmap v3

### ISSUE THREAD

**Issue by ricardogobbosouza** [webpack-contrib/eslint-webpack-plugin#82]
- [x] Add support a [`experiments.lazyCompilation
`](https://webpack.js.org/configuration/experiments/#experimentslazycompilation) 🤔  (only when not experimental)
- [x] Drop support webpack 4
- [x]  Update documentation

**Comment by screetBloom** [comment]
@ricardogobbosouza  
The `experiments.lazyCompilation` is still not supported in the lintDirtyModulesOnly mode

Is it a bug ?
