### ISSUE TITLE
Force `NODE_ENV` production for the plugin

### ISSUE THREAD

**Issue by jancama2** [webpack-contrib/eslint-webpack-plugin#89]
- Operating System: macOS Catalina 10.15.7
- Node Version: 12.19.0
- Yarn Version: 1.22.10
- webpack Version: 4.44.2
- eslint-webpack-plugin Version: 2.5.2

### Feature Proposal
Ability to force enviroment for eslint via plugin options.

### Feature Use Case
I have `eslint-plugin-compat` which uses my browserslist settings and picks the correct one according to `NODE_ENV`. In development I want to use `NODE_ENV=development` but I would like to specifically force production env for the ESLint plugin to see compatibility errors based on the production browsers.

**Comment by alexander-akait** [comment]
You can setup it on own side, I think it is out of scope the plugin

**Comment by jancama2** [comment]
Can't see a way how to do it, I would have to set `NODE_ENV` for the whole build script running webpack which i don't wan't.

**Comment by alexander-akait** [comment]
You can setup eslint plugin to use special browserslist for dev env

**Comment by alexander-akait** [comment]
Changing `NODE_ENV` is not safe and can break debug or some code, so we can't do it
