### ISSUE TITLE
Cannot read property 'run' of undefined

### ISSUE THREAD

**Issue by ntd0609** [webpack-contrib/eslint-webpack-plugin#91]
/node_modules/eslint-webpack-plugin/dist/index.js:51
      compiler.hooks.run.tapPromise(ESLINT_PLUGIN, this.run);
                     ^
TypeError: Cannot read property 'run' of undefined
---------------------------------------
I used webpack 3 and after run error
,do this plugin still support webpack version 3.xxx ?
sorry but I cant find document wide support of this plugin

**Comment by jsg2021** [comment]
I don't speak for the maintainer, but i highly doubt it. The tests only cover 4 & 5. You should stick to the loader if you're on 3 and cannot update.

**Comment by alexander-akait** [comment]
webpack v3 is not supported, please update webpack to v5 (recommend) or v4

**Comment by ntd0609** [comment]
Thanks ,  I had rollback to loader and run normal.
