### ISSUE TITLE
Add configFile path option

### ISSUE THREAD

**Issue by weilinzung** [webpack-contrib/eslint-webpack-plugin#98]
On the eslint-loader there is `configFile` option which this latest plugin doesn't?

https://github.com/webpack-contrib/eslint-loader#defining-configfile-or-using-eslint--c-patheslintrc

We have a CLI which needs to have a global config file rather than add the configuration(file) to each project.
If this plugin has that option would be great, thanks!

**Comment by ricardogobbosouza** [comment]
Hi @weilinzung 
You can use `overrideConfigFile`
See https://eslint.org/docs/developer-guide/nodejs-api#%E2%97%86-new-eslint-options
