### ISSUE TITLE
Feature/bug?: Support webpack's lazyCompilation with plugin's lintDirtyModulesOnly

### ISSUE THREAD

**Issue by grumd** [webpack-contrib/eslint-webpack-plugin#99]
- webpack Version: 5.17.0+
- eslint-webpack-plugin Version: 2.5.4

Webpack now has an experimental option { experiments: { lazyCompilation: true } }.
It works together with code-splitting and doesn't compile lazy-loaded modules that aren't needed yet.
eslint-webpack-plugin assumes only the first compilation should be skipped when lintDirtyModulesOnly is true.
With this new webpack option it doesn't work as expected.
It skips eslint checks on the initial compilation, but any lazy-loaded successor compilation will be linted.
eslint-webpack-plugin needs a new way of identifying which modules are dirty and need to be checked.

**Comment by ricardogobbosouza** [comment]
Hi @grumd 
As it is an experimental thing, it is not yet supported.
Maybe in v3 https://github.com/webpack-contrib/eslint-webpack-plugin/issues/82
